repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: npx @biomejs/biome check
        language: system
        types: [javascript, ts]
        pass_filenames: false
