# Khanqah Rush shortcuts. Run `make help` for the list.
# Reads .env when present (values are never printed or committed).
# More targets (wasm, deploy, bot ops) land with later phases.

ifeq ($(OS),Windows_NT)
SHELL := sh.exe
endif

ifneq (,$(wildcard .env))
include .env
export
endif

.DEFAULT_GOAL := help

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(firstword $(MAKEFILE_LIST)) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-14s %s\n", $$1, $$2}'

install: ## Clean dependency install (CI equivalent)
	npm ci

dev: ## Start the Vite dev server
	npm run dev

build: ## Vite build into dist/
	npm run build

preview: ## Preview the production build locally
	npm run preview

verify: check test lint build ## Run the full CI sequence locally

test: ## Run Vitest suites
	npm test

check: ## Syntax-check plain-JS runtimes
	npm run check

lint: ## Lint + format check (biome)
	npm run lint

format: ## Format everything in place (biome)
	npm run format

tasks: ## List open Tigo tasks by priority
	tigo -c list

clean: ## Remove build outputs (regenerated by build)
	rm -rf dist
